'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

const stages = [
  ['01','DISCOVER','Find the direction that fits where you want to go.','Explore study paths, destinations, courses and career guidance in one clear starting point.','/counselling',['Career guidance','Study paths','Destinations','Courses']],
  ['02','PREPARE','Turn ambition into a plan you can practise.','Build exam confidence with structured NEET preparation, mock tests and subject practice.','/exam-preparation',['180 questions','180 minutes','720 marks','3 free attempts']],
  ['03','APPLY','Move from shortlist to next step with clarity.','Discover supported destinations and get guidance as you compare your options.','/admissions',['Global admissions','Destination discovery','University shortlisting','Admission guidance']],
  ['04','LEARN','Keep building what comes next.','Find practical courses and future skills that extend your journey beyond one exam.','/courses',['Courses','AI & future skills','Learning resources','Marketplace']],
  ['05','SUCCEED','Keep moving with support around you.','Track progress, find resources and choose the next useful step with confidence.','/student',['Progress','Readiness','Direction','Continued support']],
] as const;
const tracks = [['MEDICINE','ENGINEERING','TECHNOLOGY','AI','BUSINESS','SCIENCE','ARTS','HUMANITIES'],['INDIA','RUSSIA','GEORGIA','VIETNAM','ARMENIA','UZBEKISTAN','KYRGYZSTAN','TAJIKISTAN','KAZAKHSTAN'],['NEET','COUNSELLING','ADMISSIONS','COURSES','FUTURE SKILLS','MARKETPLACE']];
function NetworkVisual({ stage }: { stage: number }) { const labels=['NEET','MEDICINE','GLOBAL ADMISSIONS','AI COURSES','ENGINEERING','FUTURE SKILLS','CAREER GUIDANCE','MARKETPLACE']; return <div className="sivora-network" aria-label="SIVORA opportunity network visualization"><div className="sivora-network-grid"/><svg className="sivora-network-lines" viewBox="0 0 700 560" aria-hidden="true"><path d="M350 280 C250 210 180 160 70 110 M350 280 C470 200 540 150 650 100 M350 280 C520 300 585 350 665 450 M350 280 C205 320 150 410 70 470 M350 280 C350 170 350 90 350 24 M350 280 C450 410 510 475 565 530"/><path className="sivora-network-flow" d="M350 280 C250 210 180 160 70 110 M350 280 C470 200 540 150 650 100 M350 280 C520 300 585 350 665 450 M350 280 C205 320 150 410 70 470"/></svg><div className="sivora-network-core"><span className="sivora-network-core-dot"/><span>SIVORA<br/><small>student journey</small></span></div>{labels.map((label,i)=><div key={label} className={`sivora-network-node sivora-network-node-${i} ${i===stage?'is-active':''}`}><span className="sivora-network-node-dot"/><span>{label}</span><small>{String(i+1).padStart(2,'0')}</small></div>)}<div className="sivora-network-readout"><span>LIVE PATH</span><strong>{stages[stage][1]}</strong><em>connected opportunity system</em></div></div>; }
export default function SivoraHomeExperience() { const [stage,setStage]=useState(0); const [phrase,setPhrase]=useState(0); const phrases=['DISCOVER YOUR PATH','PREPARE WITH PURPOSE','STUDY BEYOND BORDERS','BUILD FUTURE SKILLS']; useEffect(()=>{const id=window.setInterval(()=>setPhrase(v=>(v+1)%phrases.length),3200);return()=>window.clearInterval(id)},[phrases.length]); return <>
<section className="sivora-product-hero"><div className="sivora-hero-glow"/><div className="mx-auto grid w-full max-w-[1600px] gap-14 px-[clamp(1rem,3vw,3rem)] pb-20 pt-20 lg:grid-cols-[0.82fr_1.18fr] lg:items-center lg:pb-28 lg:pt-28"><div className="relative z-10"><p className="sivora-kicker">SIVORA UP↑RISING <span>•</span> STUDENT PLATFORM</p><h1 className="sivora-product-title">RISE BEYOND<br/><span>BOUNDARIES.</span></h1><p className="sivora-product-lede">Education, preparation and global opportunity, connected in one student journey.</p><p className="sivora-rotating-line" aria-live="polite">{phrases[phrase]}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/counselling" className="sivora-button sivora-button-red">Get guidance <span>↗</span></Link><Link href="#journey" className="sivora-button sivora-button-ghost">Explore the journey</Link></div><div className="sivora-hero-meta"><span>01</span><span>Built for the next step</span><span className="sivora-meta-line"/></div></div><NetworkVisual stage={stage}/></div></section>
<section className="sivora-marquee-section"><div className="mx-auto w-full max-w-[1600px] px-[clamp(1rem,3vw,3rem)]"><p className="sivora-kicker">EXPLORE OPPORTUNITIES</p></div>{tracks.map((track,i)=><div key={i} className={`sivora-track sivora-track-${i}`}><div>{[...track,...track].map((item,j)=><span key={`${item}-${j}`}>{item}<b>✳</b></span>)}</div></div>)}</section>
<section id="journey" className="sivora-journey-section"><div className="mx-auto w-full max-w-[1600px] px-[clamp(1rem,3vw,3rem)]"><div className="sivora-section-intro"><p className="sivora-kicker">THE SIVORA STUDENT JOURNEY</p><h2>YOUR JOURNEY.<br/><span>CONNECTED.</span></h2><p>One platform for the decisions that shape what comes next.</p></div><div className="sivora-journey-layout"><div className="sivora-stage-nav" role="tablist" aria-label="Student journey stages">{stages.map((item,i)=><button key={item[1]} type="button" role="tab" aria-selected={stage===i} onClick={()=>setStage(i)} className={stage===i?'is-active':''}><span>{item[0]}</span>{item[1]}<i/></button>)}</div><div className="sivora-stage-panel"><NetworkVisual stage={stage}/><div className="sivora-stage-copy"><p className="sivora-kicker">{stages[stage][0]} / {stages[stage][1]}</p><h3>{stages[stage][2]}</h3><p>{stages[stage][3]}</p><div className="sivora-stage-items">{stages[stage][5].map(item=><span key={item}>✓ {item}</span>)}</div><Link href={stages[stage][4]} className="sivora-text-link">Explore {stages[stage][1].toLowerCase()} <span>↗</span></Link></div></div></div></div></section>
<section className="sivora-explore-section"><div className="mx-auto w-full max-w-[1600px] px-[clamp(1rem,3vw,3rem)]"><div className="sivora-section-intro"><p className="sivora-kicker">ONE PLATFORM. MORE POSSIBILITIES.</p><h2>EXPLORE<br/><span>SIVORA.</span></h2></div><div className="sivora-product-grid">{[['01','Admissions','Study beyond borders.','/admissions'],['02','Counselling','Find your direction.','/counselling'],['03','Exam preparation','Prepare with purpose.','/exam-preparation'],['04','Courses & future skills','Keep learning what comes next.','/courses'],['05','Marketplace','Tools for the road ahead.','/marketplace']].map(([n,t,d,h])=><Link className="sivora-product-card" href={h} key={t}><span>{n}</span><strong>{t}</strong><p>{d}</p><b>↗</b></Link>)}</div></div></section>
<section className="sivora-proof-section"><div className="mx-auto grid w-full max-w-[1600px] gap-12 px-[clamp(1rem,3vw,3rem)] lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><p className="sivora-kicker">REAL CAPABILITIES. CLEAR NEXT STEPS.</p><h2>Built around<br/><span>your progress.</span></h2></div><div className="sivora-proof-grid"><div><strong>3</strong><span>FREE NEET ATTEMPTS</span></div><div><strong>180</strong><span>QUESTIONS IN A FULL MOCK</span></div><div><strong>3</strong><span>INTERFACE LANGUAGES</span></div></div></div></section>
<section className="sivora-final-cta"><div className="mx-auto flex w-full max-w-[1600px] flex-col gap-9 px-[clamp(1rem,3vw,3rem)] sm:flex-row sm:items-end sm:justify-between"><div><p className="sivora-kicker">SIVORA UP↑RISING</p><h2>RISE BEYOND<br/><span>BOUNDARIES.</span></h2></div><div><p className="max-w-sm text-base leading-7 text-[#a9a39a]">Start with one question. Leave with a clearer next step.</p><Link href="/counselling" className="sivora-button sivora-button-red mt-7">Get guidance <span>↗</span></Link></div></div></section></>; }
