import { getTranslations } from 'next-intl/server';
import Link from 'next/link';
import { pageMetadata } from '@/lib/seo';
import CounsellingVisual from '@/components/public/CounsellingVisual';
import HomeLeadForm from '@/components/public/HomeLeadForm';
import WhatsAppLink from '@/components/whatsapp/WhatsAppLink';
import { PrimaryLink, Section } from '@/components/public/ui';
import styles from '@/components/public/RouteExperience.module.css';

export async function generateMetadata() {
  const t = await getTranslations('seo.counselling');
  return pageMetadata({ title: t('title'), description: t('description'), path: '/counselling' });
}

const guidanceAreas = [
  ['CAREER DIRECTION', 'Understand interests and goals, explore realistic career pathways, identify suitable fields of study, and make an education plan with course-selection guidance.'],
  ['AFTER SCHOOL GUIDANCE', 'Consider options after Class 10 and Class 12, stream and course direction, entrance-exam routes, and college or university pathways.'],
  ['COMPETITIVE EXAM GUIDANCE', 'Understand NEET and JEE preparation pathways, the requirements behind focused preparation, and where SIVORA Exam Preparation can help.'],
  ['ADMISSION GUIDANCE', 'Explore India and international education pathways, universities and courses, destinations, applications, documents and processes.'],
];

const journey = ['Understand the student', 'Explore suitable pathways', 'Compare realistic options', 'Build an education and action plan', 'Connect to preparation or admissions support', 'Continue guidance as the student progresses'];

export default function CounsellingPage() {
  return <div className={styles.page}>
    <section className="border-b border-border"><div className="mx-auto grid max-w-[1504px] gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.82fr_1.18fr] lg:items-center lg:px-12 lg:py-28"><div><p className="text-xs font-bold tracking-[.2em] text-brand">COUNSELLING & CAREER GUIDANCE</p><h1 className="mt-5 max-w-3xl text-[clamp(3.6rem,7vw,7.5rem)] font-semibold leading-[.84] tracking-[-.075em] text-[#10151c]">Clarity before the next step.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#5f6975]">SIVORA helps students and families understand education, career, exam and admissions pathways before making important decisions.</p><div className="mt-8 flex flex-wrap gap-3"><PrimaryLink href="#talk">Talk to SIVORA</PrimaryLink><Link href="/admissions" className="inline-flex items-center justify-center border border-[#d9dee5] px-5 py-3 text-sm font-semibold text-[#10151c] transition hover:border-brand hover:text-brand">Explore Admissions</Link></div></div><CounsellingVisual /></div></section>

    <Section id="guidance"><div className="grid gap-10 lg:grid-cols-[.55fr_1.45fr]"><div><p className="text-xs font-bold tracking-[.2em] text-brand">FOR STUDENTS & PARENTS</p><h2 className="mt-5 max-w-md text-[clamp(3rem,5vw,5.7rem)] font-semibold leading-[.88] tracking-[-.07em] text-[#10151c]">Guidance that starts with your situation.</h2><p className="mt-6 max-w-sm text-[#5f6975]">Every conversation is about the next practical decision—not a guaranteed outcome.</p></div><div className="border-t border-[#d9dee5]">{guidanceAreas.map(([title, copy], index) => <article key={title} className="grid gap-4 border-b border-[#d9dee5] py-7 sm:grid-cols-[48px_.65fr_1.35fr] sm:gap-7"><span className="text-xs text-[#7a8795]">0{index + 1}</span><h3 className="text-2xl font-semibold tracking-[-.045em] text-[#10151c]">{title}</h3><p className="text-sm leading-7 text-[#5f6975]">{copy}</p></article>)}</div></div></Section>

    <Section tinted><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-xs font-bold tracking-[.2em] text-brand">INTERNATIONAL EDUCATION</p><h2 className="mt-5 text-[clamp(2.8rem,4.8vw,5.2rem)] font-semibold leading-[.9] tracking-[-.065em] text-[#10151c]">Explore the pathway before the paperwork.</h2></div><div className="border-l-2 border-brand pl-6"><p className="max-w-2xl text-lg leading-8 text-[#3d5066]">For families considering education abroad, SIVORA can help with destination exploration, university and course selection, application planning, documentation, admission processes and understanding available pathways.</p><p className="mt-6 max-w-2xl text-sm leading-7 text-[#5f6975]">Final admission, eligibility, visa, university and government decisions remain with the relevant institutions and authorities.</p><Link href="/admissions" className="mt-7 inline-block border-b border-current pb-1 text-sm font-semibold text-brand">Explore Admissions pathways →</Link></div></div></Section>

    <Section><div><p className="text-xs font-bold tracking-[.2em] text-brand">PERSONALISED GUIDANCE JOURNEY</p><h2 className="mt-5 max-w-4xl text-[clamp(3rem,5vw,5.8rem)] font-semibold leading-[.88] tracking-[-.07em] text-[#10151c]">A connected path, not a one-time answer.</h2><div className="mt-12 border-l border-[#2774e6]">{journey.map((step, index) => <div key={step} className="grid gap-3 border-b border-[#d9dee5] py-6 pl-6 sm:grid-cols-[58px_1fr] sm:items-center"><span className="text-xs font-bold tracking-[.12em] text-brand">0{index + 1}</span><p className="text-2xl font-semibold tracking-[-.04em] text-[#10151c]">{step}</p></div>)}</div></div></Section>

    <Section tinted><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-xs font-bold tracking-[.2em] text-brand">ONE CONNECTED ECOSYSTEM</p><h2 className="mt-5 text-[clamp(2.8rem,4.8vw,5.2rem)] font-semibold leading-[.9] tracking-[-.065em] text-[#10151c]">Guidance can lead somewhere useful.</h2></div><p className="max-w-2xl text-lg leading-8 text-[#5f6975]">When appropriate, counselling can connect a student to Admissions for suitable pathways, Exam Preparation for NEET or JEE preparation, Courses for structured learning pathways, and the future Marketplace for learning resources.</p></div></Section>

    <section className="bg-[#07111f] px-5 py-20 text-[#edf6ff] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1504px]"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-xs font-bold tracking-[.2em] text-[#75aaff]">PARTNER WITH SIVORA</p><h2 className="mt-5 text-[clamp(3rem,5vw,5.8rem)] font-semibold leading-[.88] tracking-[-.07em]">Support more students, together.</h2></div><p className="max-w-2xl text-lg leading-8 text-[#b8c5d4]">Education consultants, counsellors, tutors, coaching centres, institutes, educators and other suitable education partners may eventually work with SIVORA to support students, parents, candidates and enquiries.</p></div><div className="mt-14 border-t border-white/20">{[['ADMISSION REFERRALS', 'Partners with candidates seeking admission opportunities may eventually work with SIVORA through the admission guidance process.'], ['COUNSELLING REFERRALS', 'Partners may refer students or parents requiring education and career guidance.'], ['COURSES', 'Approved educators and institutes may eventually offer structured courses through SIVORA.'], ['MARKETPLACE', 'Approved partners may eventually offer educational materials and learning resources through SIVORA Marketplace.']].map(([title, copy], index) => <article key={title} className="grid gap-4 border-b border-white/20 py-7 sm:grid-cols-[48px_.6fr_1.4fr] sm:gap-7"><span className="text-xs text-[#8fa2ba]">0{index + 1}</span><h3 className="text-2xl font-semibold tracking-[-.045em]">{title}</h3><p className="text-sm leading-7 text-[#b8c5d4]">{copy}</p></article>)}</div><div className="mt-10 flex flex-wrap items-center justify-between gap-5 border border-white/20 bg-white/5 p-6"><div><p className="text-xs font-bold tracking-[.16em] text-[#75aaff]">PARTNER ONBOARDING — COMING SOON</p><p className="mt-2 max-w-xl text-sm leading-7 text-[#b8c5d4]">Partner participation will be subject to approval, appropriate review, policies and future commercial terms. Partner Portal — Coming Soon.</p></div><WhatsAppLink label="Discuss a partnership" message="Hello SIVORA, I would like to discuss a future partnership opportunity." className="inline-flex items-center justify-center border border-[#75aaff] px-5 py-3 text-sm font-semibold text-[#edf6ff] transition hover:bg-[#75aaff] hover:text-[#07111f]">Discuss a partnership</WhatsAppLink></div></div></section>

    <Section id="talk"><div className="grid gap-10 border border-[#d9dee5] bg-white p-6 sm:p-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold tracking-[.2em] text-brand">TALK TO SIVORA</p><h2 className="mt-5 text-[clamp(2.8rem,5vw,5.5rem)] font-semibold leading-[.9] tracking-[-.065em] text-[#10151c]">Start with the question in front of you.</h2><p className="mt-6 max-w-md text-[#5f6975]">Tell us what you are exploring and the team can guide your next conversation.</p><WhatsAppLink label="Talk to a counsellor" message="Hello SIVORA, I would like to speak with a counsellor about education and career guidance." className="mt-7 inline-flex items-center justify-center border border-[#25D366]/50 bg-[#25D366]/10 px-5 py-3 text-sm font-semibold text-[#176537]">Talk to a counsellor</WhatsAppLink></div><div className={styles.form}><HomeLeadForm /></div></div></Section>
  </div>;
}
