import { afterEach, describe, it, expect, vi, beforeEach } from 'vitest';
const m=vi.hoisted(()=>({session:vi.fn(),test:vi.fn(),active:vi.fn(),attempts:vi.fn(),credit:vi.fn(),paymentCreate:vi.fn(),paymentUpdate:vi.fn(),order:vi.fn(),keys:vi.fn(),log:vi.fn()}));
vi.mock('@/lib/auth/session',()=>({getSession:m.session})); vi.mock('@/lib/prisma',()=>({prisma:{test:{findUnique:m.test},testAttempt:{findFirst:m.active,count:m.attempts},paidAttemptCredit:{findFirst:m.credit},payment:{create:m.paymentCreate,update:m.paymentUpdate}}})); vi.mock('@/lib/payments/razorpay',()=>({createOrder:m.order,getKeys:m.keys})); vi.mock('@/lib/payments/service',()=>({logOrderCreated:m.log}));
import { POST } from '@/app/api/payments/retry-order/route';
const req=(body:unknown)=>new Request('http://localhost/api/payments/retry-order',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
const originalPaidRetriesFlag = process.env.EXAM_PAID_RETRIES_ENABLED;
afterEach(()=>{if(originalPaidRetriesFlag===undefined) delete process.env.EXAM_PAID_RETRIES_ENABLED; else process.env.EXAM_PAID_RETRIES_ENABLED=originalPaidRetriesFlag;});
beforeEach(()=>{process.env.EXAM_PAID_RETRIES_ENABLED='false';vi.clearAllMocks();m.session.mockResolvedValue({sub:'s1',kind:'student'});m.test.mockResolvedValue({id:'t1',isPublished:true,contentClass:'PRODUCTION'});m.active.mockResolvedValue(null);m.attempts.mockResolvedValue(3);m.credit.mockResolvedValue(null);m.paymentCreate.mockResolvedValue({id:'p1'});m.order.mockResolvedValue({id:'o1',amount:3000,mock:true});m.paymentUpdate.mockResolvedValue({});m.keys.mockReturnValue({keyId:'key'});});
describe('retry order',()=>{it('rejects checkout creation while free access is enabled',async()=>{expect((await POST(req({testId:'t1'}))).status).toBe(403);expect(m.paymentCreate).not.toHaveBeenCalled()});it('requires auth',async()=>{m.session.mockResolvedValue(null);expect((await POST(req({testId:'t1'}))).status).toBe(401)});it.each([0,1,2])('rejects while %s free attempts remain in paid mode',async n=>{process.env.EXAM_PAID_RETRIES_ENABLED='true';m.attempts.mockResolvedValue(n);expect((await POST(req({testId:'t1'}))).status).toBe(409);expect(m.paymentCreate).not.toHaveBeenCalled()});it('creates a server priced retry after three attempts in paid mode',async()=>{process.env.EXAM_PAID_RETRIES_ENABLED='true';expect((await POST(req({testId:'t1',amount:1,currency:'USD',studentId:'other',purpose:'TEST_PURCHASE'}))).status).toBe(200);expect(m.paymentCreate).toHaveBeenCalledWith({data:expect.objectContaining({studentId:'s1',purpose:'PAID_RETRY',amount:30,currency:'INR'})});expect(m.order).toHaveBeenCalledWith(expect.objectContaining({amountPaise:3000,currency:'INR'}))});it('rejects active attempt or credit in paid mode',async()=>{process.env.EXAM_PAID_RETRIES_ENABLED='true';m.active.mockResolvedValue({id:'a1'});expect((await POST(req({testId:'t1'}))).status).toBe(409);m.active.mockResolvedValue(null);m.credit.mockResolvedValue({id:'c1'});expect((await POST(req({testId:'t1'}))).status).toBe(409)});});
