import { getAdmissionsAdminSession } from '@/lib/admission/admin-session';
import { redirect } from 'next/navigation';
import { buildAdmissionsEnquiryWhere } from '@/lib/admission/enquiries-filter';
import { prisma } from '@/lib/prisma';
import { AdminCard, AdminPageHeader, Badge } from '@/components/admin/ui';
import ContactStatusSelect from '@/components/admin/ContactStatusSelect';
import { getWhatsAppUrl } from '@/lib/whatsapp';

const statuses = ['ALL', 'NEW', 'RESPONDED', 'CLOSED'] as const;

export default async function ContactEnquiriesPage({ searchParams }: { searchParams: Promise<{ status?: string; q?: string }> }) {
  if (!await getAdmissionsAdminSession()) redirect('/admin/login');
  const params = await searchParams;
  const requested = params.status;
  const status = statuses.includes(requested as typeof statuses[number]) ? requested : 'ALL';
  const enquiries = await prisma.contactEnquiry.findMany({ where: buildAdmissionsEnquiryWhere(status, params.q), orderBy: { createdAt: 'desc' }, take: 200 });
  return <div><AdminPageHeader title="Lead Inbox" description="Public admissions, callback and contact enquiries. Review consent and preferred contact method before following up." /><div className="mb-5 flex flex-wrap gap-2">{statuses.map((item) => <a key={item} href={`/admin/contact-enquiries?${new URLSearchParams({ status: item, q: params.q ?? '' })}`} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${status === item ? 'border-brand bg-brand text-white' : 'border-border text-textSecondary'}`}>{item === 'ALL' ? 'All' : item}</a>)}</div><form action="/admin/contact-enquiries" className="mb-5 flex flex-wrap gap-3"><input type="hidden" name="status" value={status} /><label className="flex min-w-0 flex-1 flex-col gap-2 text-sm text-textSecondary">Search name, contact, programme or reference<input name="q" defaultValue={params.q ?? ''} maxLength={120} className="min-h-11 rounded-md border border-border bg-surface px-3" /></label><button className="self-end rounded-md bg-brand px-4 py-3 text-white">Search inbox</button></form><div className="space-y-3">{enquiries.map((lead) => { const whatsapp = getWhatsAppUrl(`Hello ${lead.name}, SIVORA is following up on your counselling enquiry.`, lead.mobile); return <AdminCard key={lead.id} className="p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0 break-words"><p className="font-semibold text-textPrimary">{lead.name}</p><p className="mt-1 text-xs text-textSecondary">Reference: SIV-{lead.id.slice(-6).toUpperCase()}</p><p className="text-sm text-textSecondary">{lead.mobile}{lead.email ? ` · ${lead.email}` : ''}</p><p className="mt-2 whitespace-pre-wrap text-sm text-textSecondary">{lead.message}</p></div><div className="flex shrink-0 flex-col items-start gap-2 sm:items-end"><Badge color={lead.status === 'NEW' ? 'blue' : lead.status === 'CLOSED' ? 'slate' : 'green'}>{lead.status}</Badge><ContactStatusSelect id={lead.id} initial={lead.status} /><time className="text-xs text-textSecondary" dateTime={lead.createdAt.toISOString()}>{lead.createdAt.toLocaleString('en-IN')}</time><div className="flex gap-2 text-xs">{!lead.message.includes('Contact preference: Email') && !lead.message.includes('Contact preference: WhatsApp') ? <a className="text-brand underline" href={`tel:${lead.mobile}`}>Call</a> : null}{lead.email ? <a className="text-brand underline" href={`mailto:${lead.email}`}>Email</a> : null}{whatsapp.url && !lead.message.includes('Contact preference: Email') && !lead.message.includes('Contact preference: Phone') ? <a className="text-brand underline" href={whatsapp.url} target="_blank" rel="noreferrer">WhatsApp</a> : null}</div></div></div></AdminCard>; })}{enquiries.length === 0 ? <AdminCard><p className="text-sm text-textSecondary">No enquiries in this view.</p></AdminCard> : null}</div></div>;
}
